### ISSUE TITLE
Unable to minimize windows

### ISSUE THREAD

**Issue by tuananh** [workspacer/workspacer#72] opened 2019-10-03 15:49 UTC
I'm unable to minimize windows with workspacer running. Any idea why?

**Comment by josteink** [comment] 2019-10-08 11:36
I'm also able to reproduce this. Will look into it, because it's really annoying.

**Comment by tuananh** [comment] 2019-12-03 02:38
hi, any update on this?

**Comment by josteink** [comment] 2019-12-03 06:57
No idea about Rick, but I've been busy with other stuff.

I've now sorted our 4-5 other things which was annoying me, so maybe I'll look into this later too.

**Comment by rickbutton** [comment] 2019-12-09 22:08
So far this is intentional. Workspacer overrides the "minimize"/"show" actions of the default window manager. i.e. it will send a "show" message to a minimized window as soon as you click minimize.

This is done to mimic xmonad-style behavior, where every window is "controlled" unless it isn't (ctrl-t). However, I can see it working the other way too, where workspacer only managed "shown" windows, which might be a better experience given Windows' quirkyness. Thoughts on this? I think this would be a small-ish code change.

**Comment by tuananh** [comment] 2019-12-10 02:41
> So far this is intentional. Workspacer overrides the "minimize"/"show" actions of the default window manager. i.e. it will send a "show" message to a minimized window as soon as you click minimize.
> 
> This is done to mimic xmonad-style behavior, where every window is "controlled" unless it isn't (ctrl-t). However, I can see it working the other way too, where workspacer only managed "shown" windows, which might be a better experience given Windows' quirkyness. Thoughts on this? I think this would be a small-ish code change.

I see. Not coming from xmonad, i don't quite understand the behavior. For other tiling manager, it will just minimize the window and re-arrange the rest.

**Comment by rickbutton** [comment] 2019-12-10 14:51
Thinking about it more overnight, I think this would be a better behavior anyway, since you don't get the weirdness of minimize->immediately re-open.

The only question is, how to handle the "full" style layouts? Currently, the ones that aren't shown are minimized, they will need to do something else instead. Maybe just change the window order?

**Comment by zolrath** [comment] 2020-06-14 01:23
This has been irking me quite a lot lately, would love to see this change!

**Comment by dalyIsaac** [comment] 2021-03-18 22:42
@Julynx Can you give #197 a try?

**Comment by Julynx** [comment] 2021-03-19 08:22
Yeah It says the change can be enabled via a config setting. Can you give me an example on how to add the minimize functionality to the settings file?

**Comment by giri-w** [comment] 2021-04-25 11:22
Can someone share their config file for implementing this 'ignore minimized windows' ?

**Comment by dalyIsaac** [comment] 2021-04-25 21:17
In #197 I've made it so you can allow minimizing windows with `context.CanMinimizeWindows = true`. However, it hasn't been merged into `master`.

**Comment by josteink** [comment] 2021-04-26 06:43
@rickbutton must approve all merges, and he haven't been around lately.

**Comment by JulioCabria** [comment] 2021-05-14 13:58
> @rickbutton must approve all merges, and he haven't been around lately.

Someone can fork this project and compile so that we can have the executable with the minimize functionality applied until @rickbutton appears? Just a suggestion...

**Comment by earnestma** [comment] 2021-05-14 17:21
> Someone can fork this project and compile so that we can have an executable with the minimize functionality applied until @rickbutton appears? Just a suggestion...

 @JulioCabria: While I haven't tried it yet, the PR seems to a build artifacted: https://github.com/rickbutton/workspacer/actions/runs/669889041

**Comment by schiltz3** [comment] 2021-05-14 21:45
> > @rickbutton must approve all merges, and he haven't been around lately.
> 
> Someone can fork this project and compile so that we can have an executable with the minimize functionality applied until @rickbutton appears? Just a suggestion...

I thought about forking the project and taking on the project, but I am definitely not good enough because I mainly do systems programming in c so a full application is a little beyond me.

I have been really enjoying playing around with my fork, adding some functionality, and redesigning the bar plugin, so if someone does want to take on the responsibility of a new "official" fork, let me know, I would love to take part in it.

**Closed** 2021-06-28 04:29 UTC
Labels: enhancement
